### ISSUE TITLE
mesu.apple.com domain

### ISSUE THREAD

**Issue by Zusier** [MoralCode/pihole-antitelemetry#3]
adding mesu.apple.com might be a good idea. It seems to ping a lot though it also seems to break downloading apps made by apple such as “news”

**Comment by MoralCode** [comment]
Do you have a link to any research that has been done on this domain? feel free to submit a PR to add it to the `domains.csv` to document what it is/does. Since it breaks things like apple news, I hesitate to put it in the main blocklist, but would be happy to accept it into the "borked" list.

Thanks for the submission!

**Comment by MoralCode** [comment]
Upon some quick research it seems like this domain is part of apples "mobile asset software update service" (essentially its used for iOS system updates). the page at https://documentation.meraki.com/General_Administration/Other_Topics/Blocking_or_Rate_Limiting_iOS_Updates lists it as a domain that should be blocked if you want to disable iOS updates (i.e. for corporate networks where the bandwidth may be an issue).

**Comment by Zusier** [comment]
I tested updates with it blocked, it doesn’t seem to stop them. You could put it in the borked list if you wish.

**Comment by MoralCode** [comment]
Did you test just app updates or system updates too? Either way it seems like the risk of this being related to something useful is pretty high so I added it to the borked list
