### ISSUE TITLE
Telemetry file is empty

### ISSUE THREAD

**Issue by SeriousM** [MoralCode/pihole-antitelemetry#5]
Hi!
Why is the file empty?
https://github.com/MoralCode/pihole-antitelemetry/blob/main/telemetry-domains.txt
It doesn't make sense to block nothing...
Thanks

**Comment by MoralCode** [comment]
Thanks for submitting an issue!

The blocking is currently split into three lists. The list you mentioned is for domains that are confirmed not to cause any issues with any other services that people might want to use. The other two lists are for domains that have either not been tested enough, or definitely break something not related to idle telemetry. This was done so that users could chose what level of blocking they want by including one or more of the lists in pihole.

While many of these domains are already in other blocklists (see the links in the readme), it seems like some are not. These lists are meant to be a way to fill in the gaps and cover some of the more newly-discovered domains that other lists may not have yet.

As this is mainly a curiosity project, I dont have time to test every domain in depth to see if it breaks anything, so for now most of the domains are in the "beta"/untested list until there is a reasonable amount of certainly that things won't break. If there's a domain that is likely not to break things and is collecting  "unnecessary" telemetry such as nearby MAC addresses, then feel free to file an issue and I will consider adding it to the main list  based on the evidence or a popular vote in favor of the domain.

Hope this helps clear things up!

**Comment by MoralCode** [comment]
I have also added an [entry to the FAQ](https://github.com/MoralCode/pihole-antitelemetry/blob/main/FAQ.md#why-is-the-blocklist-empty) about this if others are curious
